name: Scan and Report
description: Scan Docker images for vulnerabilities (CVEs) and generate an aggregated vulnerability report.
inputs:
  image-ref:
    description: The Docker image to scan.
    required: true
  blocking-level:
    description: Level of pipeline blocking
    options:
        - 0 # None
        - 1 # Fixable critical
        - 2 # Critical/fixable high
        - 3 # Critical/high/fixable medium
        - 4 # Critical/high/Medium/fixable Low
        - 5 # All
    default: 3
runs:
  using: composite
  steps:
    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: image
        image-ref: ${{ inputs.image-ref }}
        scanners: vuln
        format: sarif
        output: cve-report.sarif
        severity: CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN
        hide-progress: true

    - name: Handle vulnerability report
      run: |
        chmod +x .github/actions/cve-scan/handle_trivy_report.sh
        .github/actions/cve-scan/handle_trivy_report.sh ${{ inputs.blocking-level }} cve-report.sarif
      shell: bash

    - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: cve-report.sarif