name: Prepare

on:
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        description: "Docker Hub username"
        type: string
        required: true
      DOCKERHUB_TOKEN:
        description: "Docker Hub token"
        type: string
        required: true

jobs:
  check-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Check DOCKERHUB_USERNAME
        run: |
          if [ -z "${{ inputs.DOCKERHUB_USERNAME }}" ]; then
              echo "❌ Value is not set."
              exit 1
          else
              echo "✅ Value exists."
          fi

      - name: Check DOCKERHUB_TOKEN
        run: |
          if [ -z "${{ inputs.DOCKERHUB_TOKEN }}" ]; then
              echo "❌ Value is not set."
              exit 1
          else
              echo "✅ Value exists."
          fi

      - name: Validate Branch Name
        run: |
          if [[ "${{ github.ref_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "✅ Branch name is valid: ${{ github.ref_name }}"
          else
            echo "❌ Branch name is invalid: ${{ github.ref_name }}"
            exit 1
          fi