name: Prepare

on:
  workflow_call:

jobs:
  check-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Set DockerHub Token as environment variables
        run: |
          echo "DOCKERHUB_TOKEN=${{ secrets.DOCKERHUB_TOKEN }}"
    
      - name: Check DOCKERHUB_USERNAME
        run: |
          if [ -z "${{ vars.DOCKERHUB_USERNAME }}" ]; then
              echo "❌ Value is not set."
              exit 1
          else
              echo "✅ Value exists."
          fi

      - name: Check DOCKERHUB_TOKEN
        run: |
          if [ -z "$DOCKERHUB_TOKEN" ]; then
              echo "❌ Value is not set."
              exit 1
          else
              echo "✅ Value exists."
          fi

      - name: Validate Branch Name
        run: |
          if [[ "${{ github.ref_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "✅ Branch name is valid: ${{ github.ref_name }}"
          else
            echo "❌ Branch name is invalid: ${{ github.ref_name }}"
            exit 1
          fi