name: Prepare

on:
  workflow_call:

jobs:
  check-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Check DOCKERHUB_USERNAME
        run: if [ -z "${{ vars.DOCKERHUB_USERNAME }}" ]; then exit 1; fi

      - name: Check DOCKERHUB_TOKEN
        run: if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then exit 1; fi

      - name: Validate Branch Name
        run: |
          if [[ ! "${{ github.ref_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Branch name is not X.X.X [${{ github.ref_name }}]"
            exit 1
          fi