name: Build Docker image

on:
  workflow_call:

jobs:
  docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # - name: Extract version from branch name
    #   run: echo "MONGO_VERSION=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to ghcr.io registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push to GHCR
      uses: docker/build-push-action@v6
      with:
        push: true
        #load: true
        build-args: MONGO_VERSION=${{ github.ref_name }}
        tags: ghcr.io/${{ github.actor }}/mongodb:${{ github.ref_name }}
        #target: test
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platform: linux/amd64
    
    # - name: Save Docker image as tarball
    #   run: docker save mongodb -o mongodb-image.tar

    # - name: Cache Docker image tarball
    #   uses: actions/cache@v4
    #   with:
    #     path: mongodb-image.tar
    #     key: ${{ runner.os }}-docker-${{ github.sha }}
    #     restore-keys: |
    #       ${{ runner.os }}-docker-