name: Build Docker image

on:
  workflow_call:

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Extract version from branch name
      run: echo "MONGO_VERSION=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build MongoDB Docker image
      uses: docker/build-push-action@v6
      with:
        push: false
        load: true
        build-args: MONGO_VERSION=${{ env.MONGO_VERSION }}
        tags: |
          mongodb:${{ env.MONGO_VERSION }}
          mongodb:latest
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Save Docker image as tarball
      run: docker save ${{ vars.DOCKERHUB_USERNAME }}/mongodb -o mongodb-image.tar

    - name: Cache Docker image tarball
      uses: actions/cache@v4
      with:
        path: mongodb-image.tar
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-