name: Build Docker image

on:
  workflow_call:

jobs:
  docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to ghcr.io registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push temp image to GHCR
      uses: docker/build-push-action@v6
      with:
        push: true
        build-args: MONGO_VERSION=${{ github.ref_name }}
        tags: ghcr.io/${{ github.actor }}/mongodb:${{ github.ref_name }}
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platform: linux/amd64