name: Smoke tests

on:
  workflow_call:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Start MongoDB container
        run: |
          docker run -d \
              --name mongodb-container \
              -p 27017:27017 \
              --health-cmd "mongosh \
              --eval 'db.runCommand({ ping: 1 })'" \
          ghcr.io/${{ github.actor }}/mongodb:${{ github.ref_name }}
    
      - name: Insert document
        run: |
          docker exec mongodb-container mongosh --eval '
            db.test.insertOne({ key:1, value:2 });
            const count = db.test.countDocuments({ key:1 });
            if (count !== 1) throw new Error();
          '

      - name: Read document
        run: |
          docker exec mongodb-container mongosh --eval '
            const doc = db.test.findOne({ key:1 });
            if (!doc || doc.value !== 2) throw new Error();
          '

      - name: Trashing container
        if: always()
        run: |
          docker stop mongodb-container || true
          docker rm mongodb-container || true