name: Smoke tests

on:
  workflow_call:

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: mongodb-image.tar
          key: ${{ runner.os }}-docker-${{ github.sha }}

      - name: Load Docker image from cached tarball
        run: docker load -i mongodb-image.tar

      - name: Start MongoDB container
        run: |
          docker run -d \
              --name mongodb-container \
              -p 27017:27017 \
              --health-cmd "mongosh \
              --eval 'db.runCommand({ ping: 1 })'" \
          mongodb
    
      - name: Write to MongoDB
        run: |
          docker exec mongodb-container mongosh --eval '
            db.test.insertOne({ name: "test", value: 123 });
            const count = db.test.countDocuments({ name: "tes" });
            if (count !== 1) throw new Error();'

      - name: Trashing container
        if: always()
        run: |
          docker stop mongodb-container || true
          docker rm mongodb-container || true