name: Vulnerability scan

on:
  workflow_call:

jobs:
  trivy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: mongodb-image.tar
          key: ${{ runner.os }}-docker-${{ github.sha }}
        
      - name: Load Docker image from cached tarball
        run: docker load -i mongodb-image.tar
        
      - name: Run Trivy Scan
        uses: ./.github/actions/trivy-scan-and-report
        with:
          image-ref: mongodb