name: Build Docker image

on:
  workflow_call:

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Metadata for Final Image Build
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.actor }}/mongodb:${{ github.ref_name }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image from ghcr.io to Docker Hub
        run: |
          IMG_NAME=mongodb
          GHCR_IMG=ghcr.io/${{ github.actor }}/$IMG_NAME:${{ github.ref_name }}
          DOCKER_IMG=${{ vars.DOCKERHUB_USERNAME }}/$IMG_NAME:${{ github.ref_name }}

          docker pull $GHCR_IMG
          docker tag $GHCR_IMG $DOCKER_IMG
          docker push $DOCKER_IMG