name: Build Docker image

on:
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        description: "Docker Hub username"
        type: string
        required: true
      DOCKERHUB_TOKEN:
        description: "Docker Hub token"
        type: string
        required: true

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Docker Hub
        run: docker login -u ${{ inputs.DOCKERHUB_USERNAME }} -p ${{ inputs.DOCKERHUB_TOKEN }}
      
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: mongodb-image.tar
          key: ${{ runner.os }}-docker-${{ github.sha }}
      
      - name: Load Docker image from cached tarball
        run: docker load -i mongodb-image.tar
    
      - name: Push image to Docker Hub
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/mongodb