name: Build Docker image

on:
  workflow_call:

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Check if credentials are set
        run: |
          if [ -z "${{ vars.DOCKERHUB_USERNAME }}" ]; then
            echo "Var DOCKERHUB_USERNAME is not set."
            exit 1
          else
            echo "Var DOCKERHUB_USERNAME exists."
          fi

          if [ -z "${{ secrets.DOCKERHUB_PASSWORD }}" ]; then
            echo "Secret DOCKERHUB_PASSWORD is not set."
            exit 1
          else
            echo "Secret DOCKERHUB_PASSWORD exists."
          fi
        
      - name: Log in to Docker Hub
        run: docker login -u ${{ vars.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: mongodb-image.tar
          key: ${{ runner.os }}-docker-${{ github.sha }}
      
      - name: Load Docker image from cached tarball
        run: docker load -i mongodb-image.tar
    
      - name: Push image to Docker Hub
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/mongodb