name: Build Docker image

on:
  workflow_call:

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version from branch name
        run: echo "MONGO_VERSION=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: mongodb-image.tar
          key: ${{ runner.os }}-docker-${{ github.sha }}
      
      - name: Load Docker image from cached tarball
        run: docker load -i mongodb-image.tar
    
      - name: Push image to Docker Hub
        run: |
          docker tag mongodb:${{ env.MONGO_VERSION }} ${{ vars.DOCKERHUB_USERNAME }}/mongodb:${{ env.MONGO_VERSION }}
          docker push mongodb:${{ env.MONGO_VERSION }}