name: Build and Test with MongoDB

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Extract version from branch name
      run: |
        # Get the version from branch name
        VERSION=${GITHUB_REF#refs/heads/}
        echo "Version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build MongoDB Docker image
      run: |
        docker build \
            --build-arg MONGO_VERSION=$VERSION \
        -t mongodb:$VERSION .
    
    - name: Start MongoDB container
      run: |
        docker run -d \
            --name mongodb-container \
            -p 27017:27017 \
            --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" \
            --health-interval 10s \
            --health-timeout 5s \
            --health-retries 3 \
        mongodb:$VERSION

    - name: Wait for MongoDB to be ready
      run: |
        for i in {1..60}; do
          if docker inspect --format='{{json .State.Health.Status}}' mongodb-container | grep -q '"healthy"'; then
            echo "MongoDB is ready!";
            break;
          fi;
          echo "Waiting for MongoDB...";
          sleep 1;
        done
        if [ $i -eq 30 ]; then
          echo "MongoDB did not become healthy in time";
          exit 1;
        fi

    - name: Run smoke tests
      run: |
        echo "Testing MongoDB connection..."
        docker exec mongodb-container mongosh --eval 'db.runCommand({ ping: 1 })' || exit 1

        echo "Inserting test data..."
        docker exec mongodb-container mongosh --eval 'db.test.insertOne({ name: "test", value: 123 })' || exit 1

        echo "Verifying test data..."
        docker exec mongodb-container mongosh --eval 'const count = db.test.countDocuments({ name: "test" }); if (count !== 1) throw new Error();' || exit 1

        echo "Smoke tests passed!"
    
    - name: Trashing container
      if: always()
      run: |
        echo "Stopping MongoDB container..."
        docker stop mongodb-container || true
        docker rm mongodb-container || true

    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: image
        image-ref: "mongodb:${{ env.VERSION }}"
        scanners: vuln
        format: json
        output: 'trivy-report.json'
        severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
        hide-progress: true
    
    - name: Display Vulnerabilities Report
      run: |
        # Function to extract vulnerabilities by severity
        get_vulnerabilities() {
          jq -r "[.Results[] | .Vulnerabilities[]? | select(.Severity == \"${1}\")]" trivy-report.json
        }

        get_nonfix_vulnerabilities() {
          echo $(get_vulnerabilities "$1" | jq '[.[] | select(.FixedVersion == null)]')
        }
        
        get_fixable_vulnerabilities() {
          echo $(get_vulnerabilities "$1" | jq '[.[] | select(.FixedVersion != null)]')
        }

        count() {
          echo "$1" | jq 'length'
        }

        print() {
          echo "$1" | jq -r '
            .[] |
            if .FixedVersion == null then
              "\(.Severity) - \(.VulnerabilityID) - \(.Title)"
            else
              "\(.Severity) - \(.VulnerabilityID) - \(.Title) - Fixed Version: \(.FixedVersion)"
            end
          ' | sort | uniq
        }

        CRIT_VULN=$(get_vulnerabilities "CRITICAL")
        CRIT_VULN_COUNT=$(count "$CRIT_VULN")
        HIGH_VULN=$(get_vulnerabilities "HIGH")
        HIGH_VULN_COUNT=$(count "$HIGH_VULN")
        MED_VULN_FIXABLE=$(get_fixable_vulnerabilities "MEDIUM")
        MED_VULN_FIXABLE_COUNT=$(count "$HIGH_VULN")

        BLOCKING_VULN_COUNT=$(($CRIT_VULN_COUNT + $HIGH_VULN_COUNT + $MED_VULN_FIXABLE_COUNT))
        if [ "$BLOCKING_VULN_COUNT" -gt 0 ]; then
          echo
          echo "Blocking vulnerabilities (aggregated)"
          echo "=============================================================================================================================="
          echo "Critical: $CRIT_VULN_COUNT"
          echo "High:     $HIGH_VULN_COUNT"
          echo "Medium:   $MED_VULN_FIXABLE_COUNT (fixable)"
          echo "=============================================================================================================================="
          print "$CRIT_VULN"
          print "$HIGH_VULN"
          print "$MED_VULN_FIXABLE"
          echo "=============================================================================================================================="
          echo "Blocking image push due to $BLOCKING_VULN_COUNT blocking vulnerabilities (critical, high, fixable medium)"
          exit 1
        fi
        
        MED_VULN_NONFIX=$(get_nonfix_vulnerabilities "MEDIUM")
        LOW_VULN=$(get_vulnerabilities "LOW")

        echo
        echo "Non-blocking vulnerabilities (aggregated)"
        echo "=============================================================================================================================="
        echo "Medium:   $(count "$MED_VULN_NONFIX")"
        echo "Low:      $(count "$LOW_VULN")"
        echo "=============================================================================================================================="
        print "$MED_VULN_NONFIX"
        print "$LOW_VULN"
        echo "=============================================================================================================================="
      shell: bash