name: Build and Test with MongoDB

on:
  push:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Extract version from branch name
      run: |
        # Get the version from branch name
        VERSION=${GITHUB_REF#refs/heads/}
        echo "Version: $VERSION"
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build MongoDB Docker image
      run: |
        docker build \
            --build-arg MONGO_VERSION=$VERSION \
        -t mongodb:$VERSION .
    
    - name: Start MongoDB container
      run: |
        docker run -d \
            --name mongodb-container \
            -p 27017:27017 \
            --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" \
            --health-interval 10s \
            --health-timeout 5s \
            --health-retries 3 \
        mongodb:$VERSION

    - name: Wait for MongoDB to be ready
      run: |
        for i in {1..60}; do
          if docker inspect --format='{{json .State.Health.Status}}' mongodb-container | grep -q '"healthy"'; then
            echo "MongoDB is ready!";
            break;
          fi;
          echo "Waiting for MongoDB...";
          sleep 1;
        done
        if [ $i -eq 30 ]; then
          echo "MongoDB did not become healthy in time";
          exit 1;
        fi

    - name: Run smoke tests
      run: |
        echo "Testing MongoDB connection..."
        docker exec mongodb-container mongosh --eval 'db.runCommand({ ping: 1 })' || exit 1

        echo "Inserting test data..."
        docker exec mongodb-container mongosh --eval 'db.test.insertOne({ name: "test", value: 123 })' || exit 1

        echo "Verifying test data..."
        docker exec mongodb-container mongosh --eval 'const count = db.test.countDocuments({ name: "test" }); if (count !== 1) throw new Error();' || exit 1

        echo "Smoke tests passed!"
    
    - name: Trashing container
      if: always()
      run: |
        echo "Stopping MongoDB container..."
        docker stop mongodb-container || true
        docker rm mongodb-container || true

    - name: Scan for vulnerabilities
      uses: aquasecurity/trivy-action@0.28.0
      with:
        scan-type: image
        image-ref: "mongodb:${{ env.VERSION }}"
        scanners: vuln
        format: json
        output: 'trivy-report.json'
        severity: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
        hide-progress: true
    
    - name: Display Vulnerabilities Report
      run: |
        # Function to extract vulnerabilities by severity
        get_vulnerabilities() {
          local severity="$1"
          jq -r "[.Results[] | .Vulnerabilities[]? | select(.Severity == \"${severity}\")]" trivy-report.json
        }

        count() {
          local vuln="$1"
          echo "$vuln" | jq 'length'
        }

        CRIT_VULN=$(get_vulnerabilities "CRITICAL")
        HIGH_VULN=$(get_vulnerabilities "HIGH")
        MED_VULN_NONFIX=$(get_vulnerabilities "MEDIUM"  | jq '.[] | select(.FixedVersion == null)')
        MED_VULN_FIXABLE=$(get_vulnerabilities "MEDIUM" | jq '.[] | select(.FixedVersion != null)')
        LOW_VULN=$(get_vulnerabilities "LOW")

        CRIT_VULN_COUNT=$(count "$CRIT_VULN")
        HIGH_VULN_COUNT=$(count "$HIGH_VULN")
        MED_VULN_NONFIX_COUNT=$(count "$MED_VULN")
        MED_VULN_FIXABLE_COUNT=$(count "$MED_VULN_FIXABLE")
        LOW_VULN_COUNT=$(count "$LOW_VULN")
        
        BLOCKING_VULN_COUNT=$(($CRIT_VULN_COUNT + $HIGH_VULN_COUNT + $MED_VULN_FIXABLE_COUNT))
        # if [ "$BLOCKING_VULN_COUNT" -gt 0 ]; then
          echo "=============================================================================================================================="
          echo "Blocking vulnerability report:"
          echo "=============================================================================================================================="
          echo "Critical: $CRIT_VULN_COUNT"
          echo "High:     $HIGH_VULN_COUNT"
          echo "Medium:   $MED_VULN_FIXABLE_COUNT (fixable)"
          echo "=============================================================================================================================="
        #   cat trivy-report.json | jq -r '.Results[] | .Vulnerabilities[]? | select(.Severity == "CRITICAL") | "CRITICAL - \(.VulnerabilityID) - \(.Title) - Fixed Version: \(.FixedVersion // "N/A")"' | sort | uniq
        #   cat trivy-report.json | jq -r '.Results[] | .Vulnerabilities[]? | select(.Severity == "HIGH")     | "HIGH     - \(.VulnerabilityID) - \(.Title) - Fixed Version: \(.FixedVersion // "N/A")"' | sort | uniq
        #   cat trivy-report.json | jq -r '.Results[] | .Vulnerabilities[]? | select(.Severity == "MEDIUM")   | select(.FixedVersion != null and .FixedVersion != "") | "MEDIUM   - \(.VulnerabilityID) - \(.Title) - Fixed Version: \(.FixedVersion)"' | sort | uniq
        #   echo "Blocking image push due to $BLOC_VULN blocking vulnerabilities (critical, high, fixable medium)"
        #   exit 1
        # fi

        # CRIT_VULN=$(jq '[.Results[] | .Vulnerabilities[]? | select(.Severity == "CRITICAL")] | length' trivy-report.json)
        # HIGH_VULN=$(jq '[.Results[] | .Vulnerabilities[]? | select(.Severity == "HIGH")]     | length' trivy-report.json)
        # MED_VULN=$(jq '[.Results[]  | .Vulnerabilities[]? | select(.Severity == "MEDIUM")]   | length' trivy-report.json)
        # LOW_VULN=$(jq '[.Results[]  | .Vulnerabilities[]? | select(.Severity == "LOW")]      | length' trivy-report.json)

        echo "No blocking vulnerabilities found"
        echo "=============================================================================================================================="
        echo "Non blocking vulnerability report:"
        echo "=============================================================================================================================="
        echo "Medium:   $MED_VULN_NONFIX_COUNT"
        echo "Low:      $LOW_VULN_COUNT"
        echo "=============================================================================================================================="
        
        # cat trivy-report.json | jq -r '.Results[] | .Vulnerabilities[]? | select(.Severity == "CRITICAL") | "CRITICAL - \(.VulnerabilityID) - \(.Title)"' | sort | uniq
        # cat trivy-report.json | jq -r '.Results[] | .Vulnerabilities[]? | select(.Severity == "HIGH")     | "HIGH     - \(.VulnerabilityID) - \(.Title)"' | sort | uniq
        # cat trivy-report.json | jq -r '.Results[] | .Vulnerabilities[]? | select(.Severity == "MEDIUM")   | "MEDIUM   - \(.VulnerabilityID) - \(.Title)"' | sort | uniq
        # cat trivy-report.json | jq -r '.Results[] | .Vulnerabilities[]? | select(.Severity == "LOW")      | "LOW      - \(.VulnerabilityID) - \(.Title)"' | sort | uniq
        
        # SEVERE_VULN=$(($CRIT_VULN + $HIGH_VULN))
        # if [ "$SEVERE_VULN" -gt 0 ]; then
        #   echo "Blocking image push due to $SEVERE_VULN severe vulnerabilities (critical, high)"
        #   exit 1
        # fi
      shell: bash

    # - name: Block image push if there is severe vulnerabilities
    #   uses: aquasecurity/trivy-action@0.28.0
    #   with:
    #     scan-type: image
    #     image-ref: "mongodb:${{ env.VERSION }}"
    #     scanners: vuln
    #     format: template
    #     template: "{{ range . }}{{- range .Vulnerabilities }}{{- $vuln = add $vuln 1 }}{{ end }}"
    #     severity: 'CRITICAL,HIGH'
    #     hide-progress: true
    #     exit-code: 1