name: Get Latest MongoDB Version

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1-5" #6am every work day
  

jobs:
  get-latest-version:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch the Latest MongoDB stable version
        run: |
          MONGO_VERSION=$(curl -s https://api.github.com/repos/mongodb/mongo/tags \
            | jq -r '.[] | select(.name | test("^r[0-9]+\\.[0-9]+\\.[0-9]+$")) | .name' \
            | head -n 1 \
            | sed 's/^r//'
          )
          echo "::set-output name=mongo_version::$MONGO_VERSION"

      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Check and Create a Branch
        id: create-new-version-branch
        run: |
          # Fetch all branches
          git fetch origin

          # Check if the branch already exists
          if git ls-remote --heads origin $MONGO_VERSION > /dev/null; then
            echo "Branch $MONGO_VERSION already exists on the remote."
            exit 0
          else
            echo "Branch '$MONGO_VERSION' does not exist. Creating it..."
            git checkout latest
            git checkout -b $MONGO_VERSION
            git push origin $MONGO_VERSION
          fi