name: Build Docker image

on:
  push:
    branches:
      - '**'
      - '!latest'

jobs:
  build-image:
    uses: ./.github/workflows/1-build-image.yml

  smoke-test:
    needs: build-image
    uses: ./.github/workflows/2a-smoke-test.yml

  vuln-scan:
    needs: build-image
    uses: ./.github/workflows/2b-vuln-scan.yml