name: Build Docker image

on:
  push:
    branches-ignore:
      - 'latest'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  validate:
    uses: ./.github/workflows/0-validate.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/1-build.yml
    secrets: inherit

  test:
    needs: build
    uses: ./.github/workflows/2-test-smoke.yml

  scan-vuln-block:
    needs: build
    uses: ./.github/workflows/2-scan-vuln-block.yml
  
  scan-vuln-report:
    needs: build
    uses: ./.github/workflows/2-scan-vuln-report.yml

  push:
    needs: [test, scan-vuln-block]
    uses: ./.github/workflows/3-push.yml
    secrets: inherit