name: Build Docker image

on:
  push:
    branches-ignore:
      - 'latest'

jobs:
  prepare:
    uses: ./.github/workflows/0-prepare.yml

  build:
    uses: ./.github/workflows/1-build-image.yml

  test:
    needs: build
    uses: ./.github/workflows/2a-smoke-test.yml

  vuln-scan:
    needs: build
    uses: ./.github/workflows/2b-vuln-scan.yml

  push:
    needs: [test, vuln-scan]
    uses: ./.github/workflows/3-push.yml  