name: Build Docker image

on:
  push:
    branches-ignore:
      - 'latest'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  validate:
    uses: ./.github/workflows/0-validate.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/1-build.yml
    secrets: inherit

  test:
    needs: build
    uses: ./.github/workflows/2a-test.yml

  scan-vuln-blocking:
    name: Scan Vulnerabilities
    needs: build
    uses: ./.github/workflows/2b-scan-blocking-vuln.yml
  
  scan-vuln-all:
    name: Scan Vulnerabilities
    needs: build
    uses: ./.github/workflows/2c-scan-all-vuln.yml

  push:
    needs: [test, scan-vuln-blocking]
    uses: ./.github/workflows/3-push.yml
    secrets: inherit