name: Build Docker image

on:
  push:
    branches-ignore:
      - 'latest'

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  validate:
    uses: ./.github/workflows/0-validate.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/1-build.yml
    secrets: inherit

  test:
    needs: build
    uses: ./.github/workflows/2a-test.yml

  scan:
    needs: build
    uses: ./.github/workflows/2b-scan.yml

  push:
    needs: [test, scan]
    uses: ./.github/workflows/3-push.yml
    secrets: inherit