name: Scan new CVEs for published versions

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * 1-5" #6am every work day

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  vuln-block:
    uses: ./.github/workflows/2-vuln-block.yml
  
  vuln-report:
    uses: ./.github/workflows/2-vuln-report.yml